on:
  push:
    tags: '*'

jobs:
  release:
    name: Build and release gem
    runs-on: ubuntu-18.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      - name: Set Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Build and release
        uses: cadwallion/publish-rubygems-action@master
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release
